### ISSUE TITLE
Não sei quantos experiências ainda faltam pra relatar.

### ISSUE THREAD

**Issue by Hateki** [HestiaProject/PAxSPL#11]
Quando estou relatando a experiências do processo, não é possível saber quantas experiências ainda faltam para relatar. É possível saber na próxima tela, mas talvez seja interessante ter o resumo na tela do print.
![experiencias](https://user-images.githubusercontent.com/6591162/84828443-72bf9900-affc-11ea-970a-19dc6f667705.png)

**Comment by lucianoMarchezan** [comment]
Fixed
