### ISSUE TITLE
Limitar tamanho mínimo e máximo do campo

### ISSUE THREAD

**Issue by rmavansi** [HestiaProject/PAxSPL#13]
Na tela de preencher informações dos membros do time é possivel alterar o tamanho do campo até ser ilegivel.

E remover o "." após "Add information" nessa mesma tela.

![image](https://user-images.githubusercontent.com/56969329/84838285-5f1e2d80-b010-11ea-8a68-4cb2c83f5449.png)

**Comment by lucianoMarchezan** [comment]
Fixed
