### ISSUE TITLE
Campo retrieval technique vazio

### ISSUE THREAD

**Issue by rmavansi** [HestiaProject/PAxSPL#19]
Ao criar uma nova atividade no domain, asset ou product do scoping process, o campo do retrieval technique está vazio, resultando em erro.

![image](https://user-images.githubusercontent.com/56969329/84925020-b7e8d700-b09f-11ea-88bd-f89ce0bfa45c.png)

![image](https://user-images.githubusercontent.com/56969329/84925066-c800b680-b09f-11ea-8302-fe473155fc23.png)

**Comment by lucianoMarchezan** [comment]
Fixed
