### ISSUE TITLE
Difícil visualisação do botão de Registro

### ISSUE THREAD

**Issue by Hateki** [HestiaProject/PAxSPL#7]
Quando fui criar uma nova conta, demorei alguns segundos para encontrar o botão de fazer o cadastro. O contraste com o fundo está ruim, fazendo com que fique difícil de ver o botão.
![Loguin](https://user-images.githubusercontent.com/6591162/84821751-f88a1700-aff1-11ea-9f84-47d5da218592.png)

**Comment by lucianoMarchezan** [comment]
Fixed
